import { Link, useParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { StatusBadge } from "@/components/common/StatusBadge";
import { ArrowLeft, Download, CheckCircle2, BookOpen, Users, Server, Loader2 } from "lucide-react";
import { useReport } from "@/hooks/useApi";

export default function ReportDetail() {
  const { id } = useParams();
  const { data: report, isLoading } = useReport(id || '');

  if (isLoading) {
    return <div className="flex items-center justify-center h-64"><Loader2 className="w-6 h-6 animate-spin text-muted-foreground" /></div>;
  }

  if (!report) {
    return (
      <div className="p-6 max-w-5xl mx-auto">
        <Button variant="ghost" size="icon" asChild><Link to="/app/reports"><ArrowLeft className="w-4 h-4" /></Link></Button>
        <p className="text-muted-foreground mt-4">Report not found.</p>
      </div>
    );
  }

  return (
    <div className="p-6 max-w-5xl mx-auto space-y-6">
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="icon" asChild><Link to="/app/reports"><ArrowLeft className="w-4 h-4" /></Link></Button>
        <div className="flex-1">
          <div className="flex items-center gap-3">
            <h1 className="text-xl font-semibold">{report.title || 'Untitled Report'}</h1>
            {report.status && <StatusBadge status={report.status} />}
          </div>
          <p className="text-sm text-muted-foreground">{report.type || 'Report'} · Generated {report.createdAt ? new Date(report.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : ''}</p>
        </div>
        <Button variant="outline" size="sm"><Download className="w-4 h-4" /> Export PDF</Button>
      </div>

      <div className="bg-card rounded-2xl border border-border shadow-card">
        <div className="p-6 border-b border-border">
          {report.status === 'finalized' && (
            <div className="flex items-center gap-2 mb-4">
              <CheckCircle2 className="w-5 h-5 text-success" />
              <Badge variant="success">Approved & Finalized</Badge>
            </div>
          )}
          <h2 className="text-2xl font-semibold font-serif">{report.title}</h2>
          {report.employeeName && <p className="text-muted-foreground mt-2">Knowledge capture summary for {report.employeeName}</p>}
        </div>

        <div className="p-6 space-y-8 font-serif">
          {report.content ? (
            <div className="text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap">{report.content}</div>
          ) : (
            <p className="text-sm text-muted-foreground">No report content available yet.</p>
          )}
        </div>

        <div className="p-6 border-t border-border">
          <div className="text-xs text-muted-foreground">
            Generated by LegacyAI{report.createdAt ? ` on ${new Date(report.createdAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}` : ''}
          </div>
        </div>
      </div>
    </div>
  );
}